name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Set version
        run: node cmd/set-version.js . ${GITHUB_REF#refs/*/}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Add npm token
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc

      - name: Publish
        if: "!github.event.release.prerelease"
        run: pnpm publish --access public --no-git-checks

      - name: Publish release candidate
        if: "github.event.release.prerelease"
        run: pnpm publish --access public --tag=canary --no-git-checks
